[workspace]
version = "0.10.0"
members = ["modules/*"]

[config]
registry_index = true
path_mode = "rbxp"

[workspace.dependencies]
Jest = "3.12.0"
JestBenchmark = "3.12.0"
JestGlobals = "3.12.0"
React = "17.1.19"
ReactRoblox = "17.1.19"
