[package]
name = "roblox/signals"
description = "Scalable and minimal reactive programming framework for Luau."
version = "0.9.0"
license = "MIT"
authors = ["Roblox <noreply@roblox.com>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
repository = "https://github.com/Roblox/signals"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dev-dependencies]
Jest = "roblox/jest@3.20.0"
JestBenchmark = "roblox/jest-benchmark@3.20.0"
JestGlobals = "roblox/jest-globals@3.20.0"
