[package]
name = "ResourcesReact"
version = { workspace = true }
publish = true
authors = ["Jonathan Kelaty <jkelaty@roblox.com>"]
content_root = "src"
files = ["*", "!jest.config.lua", "!**/__tests__/**"]

[dependencies]
React = { workspace = true }
Resources = { path = "../resources" }

[dev_dependencies]
Jest = { workspace = true }
JestGlobals = { workspace = true }
ReactRoblox = { workspace = true }
