[package]
name = "SignalsImplicitScope"
version = { workspace = true }
publish = false
authors = ["Jonathan Kelaty <jkelaty@roblox.com>"]
content_root = "src"
files = ["*", "!jest.config.lua", "!**/__tests__/**"]

[dependencies]
Signals = { path = "../signals" }

[dev_dependencies]
Jest = { workspace = true }
JestGlobals = { workspace = true }
