name: analyze

on:
  pull_request_target:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Install foreman
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Tool check
        run: |
          foreman list

      - name: Install packages
        run: |
          wally install

      - name: Lint check
        run: |
          selene modules

      - name: Style check
        run: |
          stylua -c modules

      - name: Generate sourcemap
        run: |
          rojo sourcemap default.project.json -o sourcemap.json

      - name: Export types
        run: |
          wally-package-types --sourcemap sourcemap.json Packages
          wally-package-types --sourcemap sourcemap.json DevPackages

      - name: Fetch types
        run: |
          curl -s -O https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/master/scripts/globalTypes.d.luau

      - name: Type check
        run: |
          luau-lsp analyze --defs globalTypes.d.luau --sourcemap sourcemap.json modules
